<?xml version="1.0" encoding="utf-8"?><Database Name="2-sem-gr-2" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Consultant_Line" Member="Consultant_Lines">
    <Type Name="Consultant_Line">
      <Column Name="Line_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Project_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="User_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hourly_Rate" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Hours_total" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Consultant_Line_Invoice" Member="Invoices" ThisKey="Line_ID" OtherKey="Line_ID" Type="Invoice" />
      <Association Name="Project_Consultant_Line" Member="Project" ThisKey="Project_ID" OtherKey="Project_ID" Type="Project" IsForeignKey="true" />
      <Association Name="User_Consultant_Line" Member="User" ThisKey="User_ID" OtherKey="User_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Invites" Member="Invites">
    <Type Name="Invite">
      <Column Name="Project_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Invite_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Invite_status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Accept_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Project_Invite" Member="Project" ThisKey="Project_ID" OtherKey="Project_ID" Type="Project" IsForeignKey="true" />
      <Association Name="User_Invite" Member="User" ThisKey="User_ID" OtherKey="User_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Project_Message_Line" Member="Project_Message_Lines">
    <Type Name="Project_Message_Line">
      <Column Name="Message_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Project_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="User_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Message_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Project_Project_Message_Line" Member="Project" ThisKey="Project_ID" OtherKey="Project_ID" Type="Project" IsForeignKey="true" />
      <Association Name="User_Project_Message_Line" Member="User" ThisKey="User_ID" OtherKey="User_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Projects" Member="Projects">
    <Type Name="Project">
      <Column Name="Project_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="User_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Project_Start_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Project_End_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Project_Modify_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Total_Invoice_Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Project_Status" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Project_Consultant_Line" Member="Consultant_Lines" ThisKey="Project_ID" OtherKey="Project_ID" Type="Consultant_Line" />
      <Association Name="Project_Invite" Member="Invites" ThisKey="Project_ID" OtherKey="Project_ID" Type="Invite" />
      <Association Name="Project_Project_Message_Line" Member="Project_Message_Lines" ThisKey="Project_ID" OtherKey="Project_ID" Type="Project_Message_Line" />
      <Association Name="Project_Projects_Specialisation_Line" Member="Projects_Specialisation_Lines" ThisKey="Project_ID" OtherKey="Project_ID" Type="Projects_Specialisation_Line" />
      <Association Name="Project_Invoice" Member="Invoices" ThisKey="Project_ID" OtherKey="Project_ID" Type="Invoice" />
      <Association Name="User_Project" Member="User" ThisKey="User_ID" OtherKey="User_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Projects_Specialisation_Line" Member="Projects_Specialisation_Lines">
    <Type Name="Projects_Specialisation_Line">
      <Column Name="Project_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Spec_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Project_Projects_Specialisation_Line" Member="Project" ThisKey="Project_ID" OtherKey="Project_ID" Type="Project" IsForeignKey="true" />
      <Association Name="Specialisation_Projects_Specialisation_Line" Member="Specialisation" ThisKey="Spec_Id" OtherKey="Spec_Id" Type="Specialisation" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Specialisations" Member="Specialisations">
    <Type Name="Specialisation">
      <Column Name="Spec_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Specialisation" Member="Specialisation1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Specialisation_Projects_Specialisation_Line" Member="Projects_Specialisation_Lines" ThisKey="Spec_Id" OtherKey="Spec_Id" Type="Projects_Specialisation_Line" />
      <Association Name="Specialisation_Specialisations_Line" Member="Specialisations_Lines" ThisKey="Spec_Id" OtherKey="Spec_Id" Type="Specialisations_Line" />
    </Type>
  </Table>
  <Table Name="dbo.Specialisations_Line" Member="Specialisations_Lines">
    <Type Name="Specialisations_Line">
      <Column Name="User_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Spec_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Specialisation_Specialisations_Line" Member="Specialisation" ThisKey="Spec_Id" OtherKey="Spec_Id" Type="Specialisation" IsForeignKey="true" />
      <Association Name="User_Specialisations_Line" Member="User" ThisKey="User_Id" OtherKey="User_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="User_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="User_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Street_Address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Zip_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Phone_Number" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Active_Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Association Name="User_Consultant_Line" Member="Consultant_Lines" ThisKey="User_ID" OtherKey="User_ID" Type="Consultant_Line" />
      <Association Name="User_Invite" Member="Invites" ThisKey="User_ID" OtherKey="User_ID" Type="Invite" />
      <Association Name="User_Project_Message_Line" Member="Project_Message_Lines" ThisKey="User_ID" OtherKey="User_ID" Type="Project_Message_Line" />
      <Association Name="User_Project" Member="Projects" ThisKey="User_ID" OtherKey="User_ID" Type="Project" />
      <Association Name="User_Specialisations_Line" Member="Specialisations_Lines" ThisKey="User_ID" OtherKey="User_Id" Type="Specialisations_Line" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="Invoice_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Project_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Line_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Total_Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Invoice_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Consultant_Line_Invoice" Member="Consultant_Line" ThisKey="Line_ID" OtherKey="Line_ID" Type="Consultant_Line" IsForeignKey="true" />
      <Association Name="Project_Invoice" Member="Project" ThisKey="Project_ID" OtherKey="Project_ID" Type="Project" IsForeignKey="true" />
    </Type>
  </Table>
</Database>